### ISSUE TITLE
Unable to reproduce your results

### ISSUE THREAD

**Issue by Vedaad-Shakib** [aireveries/RarePlanes#10]
We are trying to reproduce your results and running into something strange. We are getting an average mAP of 73.15 when training with all of the real data, as expected, but the issue is that our training converges around 5k-15k iterations and then decreases, as opposed to the 60k iterations for convergence mentioned in the paper. 

We are training with the exact same parameters as specified in the Rareplanes paper, and our mAP graph is attached. We suspect that the reason our results differ from yours is that we may have picked a higher batch size than you did. We chose a batch size of 32. 

Can you please let us know what batch size you used for the experiment with the real data? Also, if possible, can you post a copy of your mAP plot for the experiment with just the real data?
<img width="357" alt="Screen Shot 2021-02-20 at 8 45 54 PM" src="https://user-images.githubusercontent.com/3393996/109229444-27a77980-7778-11eb-988b-12c4b300a944.png">

**Comment by thomashossler** [comment]
We used a batch size of 16. As mentioned in the paper, we use detectron2 to perform the experiments but we have a modified version of the library that supports Albumentations. 

![image](https://user-images.githubusercontent.com/20665707/112377199-ad98e080-8ca2-11eb-98c5-8913b30b0ae6.png)

with a crop_size of 512, crop_type is absolute. The list of augmentations is called as follow:


![image](https://user-images.githubusercontent.com/20665707/112377231-b5f11b80-8ca2-11eb-8dc9-5cfb1921087a.png)
