### ISSUE TITLE
Minimal code to run inference on single image

### ISSUE THREAD

**Issue by hp2304** [aireveries/RarePlanes#11]
I am looking to run inference on a single image and get its results; can you provide **minimal code** to do that. I see code regarding this task on other issues but unable to follow (haven't used detectron2 before).

Task overview:
1. Load model
2. Read Input Image
3. Preprocess input image
4. Fetch results by running forward pass.

**Comment by thomashossler** [comment]
This [notebook](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5
) should show how to run inferences using Detectron2 and this [issue](https://github.com/aireveries/RarePlanes/issues/7) should tell you which config to use

**Comment by hp2304** [comment]
Thanks for sharing this.

**Comment by hp2304** [comment]
The [link](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5) provided by Thomas Hossler
