### ISSUE TITLE
Synthetic data for military aircraft??

### ISSUE THREAD

**Issue by SkySpy1964** [aireveries/RarePlanes#2]
It seems there is presently no synthetic data available in either the training or testing data for the military aircraft classes.  Is that correct?

If so, will there be any future updates for adding synthetic data for the military aircraft?

Given the very large imbalance between the civilian and military sample sizes, it would seem that generating synthetic data for the military aircraft would be beneficial for training more robust models.

**Comment by thomashossler** [comment]
It's correct but we will not be providing synthetic for military aircraft.
