### ISSUE TITLE
dataset access

### ISSUE THREAD

**Issue by time-iter** [aireveries/RarePlanes#6]
I don‘t have an aws account, could you provide some directly download urls.

**Comment by thomashossler** [comment]
We feel like AWS is the easiest way to access the data. You can create an account here: https://aws.amazon.com/premiumsupport/knowledge-center/create-and-activate-aws-account/

**Comment by bisraelsen** [comment]
You do not need an aws account to download the data if you use the `--no-sign-request` option. For example:
`aws s3 sync s3://rareplanes-public/real/train/PS-RGB/ real/train/PS-RGB/ --no-sign-request` works.
