### ISSUE TITLE
No airplanes are detected using the pretrained model even with images from training set!

### ISSUE THREAD

**Issue by hamadichihaoui** [aireveries/RarePlanes#7]
Hello,

I used the following code to test your pretrained models using images from the training set but if fails.

`cfg = get_cfg()

cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_1x.yaml"))
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.1  # set threshold for this model
cfg.MODEL.WEIGHTS = 'model_0043999.pth' 
predictor = DefaultPredictor(cfg)
outputs = predictor(im)
print(outputs)

v = Visualizer(im[:, :, ::-1], MetadataCatalog.get(cfg.DATASETS.TRAIN[0]), scale=1.2)
out = v.draw_instance_predictions(outputs["instances"].to("cpu`

**Comment by Vedaad-Shakib** [comment]
Hi, I'm getting the same issue.

I also registered the real train and test datasets and ran 
```
evaluator = COCOEvaluator("test", cfg, False)
val_loader = build_detection_test_loader(cfg, "test")
print(inference_on_dataset(predictor.model, val_loader, evaluator))
```

but the output says "WARNING [09/28 03:30:21 d2.evaluation.coco_evaluation]: No predictions from the model!"

**Comment by Vedaad-Shakib** [comment]
@hamadichihaoui The issue was that you need to add `cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1` to your code.

**Comment by hamadichihaoui** [comment]
@Vedaad-Shakib it works! thanks..
